name: gasox
description: GASOX - Detector de Humo con ESP32

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4
  wifi_scan: ^0.4.1
  network_info_plus: ^6.1.4
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.1
  workmanager: ^0.6.0
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.6
  multicast_dns: ^0.3.3
  audioplayers: ^5.2.1
  file_picker: ^8.1.4
  vibration: ^3.1.3
  flutter_launcher_icons: ^0.14.4
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/banners/
    - assets/sounds/alarm1.mp3
    - assets/sounds/alarm2.mp3
    - assets/sounds/alarm3.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/regular.otf
          weight: 400
        - asset: assets/fonts/manrope/medium.otf
          weight: 500
        - asset: assets/fonts/manrope/bold.otf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  min_sdk_android: 21